CommandCenter/CommandCenter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mainApp.urls", namespace="main")),
    path(
        "pigeon_interrupts/",
        include("pigeonInterrupts.urls", namespace="pigeon_interrupts"),
    ),
    path("weather/", include("weatherApp.urls", namespace="weather_conditions")),
]

CommandCenter/mainApp/urls.py
from django.urls import path
from . import views

app_name = "mainApp"
urlpatterns = [
    path("", views.home_view, name="home"),
]

CommandCenter/pigeonInterrupts/urls.py
from django.urls import path
from . import views

app_name = "pigeonInterrupts"
urlpatterns = [
    path("", views.home_view, name="home"),
    path("list/", views.pigeon_interrupt_list_view, name="pigeon_interrupt_list"),
    path(
        "delete/<int:id>/",
        views.pigeon_interrupt_delete_view,
        name="pigeon_interrupt_delete",
    ),
]

CommandCenter/weatherApp/urls.py
from django.urls import path
from . import views

app_name = "weatherApp"
urlpatterns = [
    path("", views.home_view, name="home"),
    path("list/", views.weather_conditions_list_view, name="weather_conditions_list"),
    path(
        "delete/<int:id>/",
        views.weather_conditions_delete_view,
        name="weather_conditions_delete",
    ),
    path(
        "create/",
        views.weather_conditions_create_view,
        name="weather_conditions_create",
    ),
    path(
        "update/<int:id>/",
        views.weather_conditions_update_view,
        name="weather_conditions_update",
    ),
]

CommandCenter/mainApp/models.py
from django.db import models

# Create your models here.

CommandCenter/mainApp/views.py
from django.shortcuts import render


# Create your views here.
def home_view(request):
    return render(request, "mainApp/home.html")

CommandCenter/mainApp/templates/mainApp/home.html
<!-- Extend the base layout from the mainApp/layout.html -->
{% extends "mainApp/layout.html" %}

{% block title %} Home {% endblock %}

{% block content %}
  <div class="jumbotron text-center">
    <h1>Welcome to the Command Center</h1>
  </div>
{% endblock %}

CommandCenter/mainApp/templates/mainApp/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} Home {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <meta name="description" content="Description of your website for SEO purposes.">
    <meta name="keywords" content="HTML, CSS, Django, Python">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
</head>
<body>
    <header>
        <h1>Command center</h1>
    </header>
    <nav>
        <ul>
            <li><a href="{% url 'mainApp:home' %}">Home page</a></li>
            <li><a href="{% url 'pigeonInterrupts:home' %}">Pigeons interrupt records</a></li>
            <li><a href="{% url 'weatherApp:home' %}">Weather contidions</a></li>
        </ul>
    </nav>

    <main>
        <div class="content">
            {% block content %}
            
            {% endblock  %}
        </div>
    </main>

    <footer class="fixed-bottom">
        <div>
        <p>2024 Command center by Jakub Styczen</p>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.min.js"></script>
</body>
</html>