CommandCenter/CommandCenter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mainApp.urls", namespace="main")),
    path(
        "pigeon_interrupts/",
        include("pigeonInterrupts.urls", namespace="pigeon_interrupts"),
    ),
    path("weather/", include("weatherApp.urls", namespace="weather_conditions")),
]

CommandCenter/mainApp/urls.py
from django.urls import path
from . import views

app_name = "mainApp"
urlpatterns = [
    path("", views.home_view, name="home"),
]

CommandCenter/pigeonInterrupts/urls.py
from django.urls import path
from . import views

app_name = "pigeonInterrupts"
urlpatterns = [
    path("", views.home_view, name="home"),
    path("list/", views.pigeon_interrupt_list_view, name="pigeon_interrupt_list"),
    path(
        "delete/<int:id>/",
        views.pigeon_interrupt_delete_view,
        name="pigeon_interrupt_delete",
    ),
]

CommandCenter/pigeonInterrupts/models.py
from django.db import models
from django.core.exceptions import ValidationError


# Create your models here.
class PigeonInterrupt(models.Model):
    """
    Model contains:
    - time of interrupt captured (or just regular data if there was no interrupt),
    - current sensors status in project: PIRSensor, CameraSensor
    """

    Time = models.DateTimeField()
    PIRSensor = models.BooleanField(default=False)
    CameraSensor = models.BooleanField(default=False)

    # Not available for djondo MongoDB database
    # class Meta:
    #     constraints = [
    #         models.CheckConstraint(
    #             check=models.Q(Time__isnull=False),
    #             name="Time_is_not_null"
    #         )
    #     ]

    def __str__(self) -> str:
        return f"Data captured at: {self.Time} with status PIRSensor: {self.PIRSensor} and CameraSensor: {self.CameraSensor}"

    def clean(self):
        if self.Time is None:
            raise ValidationError("Date must be not None")

CommandCenter/pigeonInterrupts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import PigeonInterrupt


# Create your views here.
def home_view(request):
    return render(request, "pigeonInterrupts/home.html")


def pigeon_interrupt_list_view(request):
    quantity_raw = request.GET.get("quantity")
    if quantity_raw != "" and quantity_raw is not None:
        quantity = int(quantity_raw)
    else:
        quantity = 5
    pigeons_interrupts = (
        PigeonInterrupt.objects.all().order_by("Time").reverse()[:quantity]
    )
    return render(
        request,
        "pigeonInterrupts/pigeon_interrupt_list.html",
        {"pigeons_interrupts": pigeons_interrupts},
    )


def pigeon_interrupt_delete_view(request, id):
    pigeon_interrupt = PigeonInterrupt.objects.get(id=id)
    if request.method == "POST":
        pigeon_interrupt.delete()
        return redirect("pigeonInterrupts:pigeon_interrupt_list")
    return render(
        request,
        "pigeonInterrupts/pigeon_interrupt_delete.html",
        {"pigeon_interrupt": pigeon_interrupt},
    )

CommandCenter/pigeonInterrupts/templates/pigeonInterrupts/home.html
<!-- Extend the base layout from the pigeonInterrupts/layout.html -->
{% extends "pigeonInterrupts/layout.html" %}

{% block title %} Pigeon deterrent {% endblock %}

{% block subcontent %}
  <div class="jumbotron text-center">
    <h1 class="display-4">Welcome to the pigeon interrupts logs</h1>
    <p class="lead">
        View pigeon interrupts logs from MongoDB.
    </p>
    <hr class="my-4">
    <a href="{% url 'pigeonInterrupts:pigeon_interrupt_list' %}" class="btn btn-primary btn-lg" role="button">View records</a>
  </div>
{% endblock %}

CommandCenter/pigeonInterrupts/templates/pigeonInterrupts/layout.html
<!-- Extend the base layout from the mainApp:layout.html -->
{% extends "mainApp/layout.html" %}
{% comment %} Used parts of tempaltes from NetNinja's django course {% endcomment %}
{% block title %} Pigeon Interrupts logs {% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="{% url 'pigeonInterrupts:home' %}">Pigeon Deterrent App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="true" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pigeonInterrupts:pigeon_interrupt_list' %}">Show recorded pigeon interrupts</a>  <!-- Link to the product listing page -->
            </li>
        </ul>
    </div>
</nav>
<div class="subcontent">
    {% block subcontent %}
    
    {% endblock  %}
</div>
{% endblock %}

CommandCenter/pigeonInterrupts/templates/pigeonInterrupts/pigeon_interrupt_delete.html
<!-- Extend the base layout from the pigeonInterrupts/layout.html -->
{% extends "pigeonInterrupts/layout.html" %}

{% block title %} Delete pigeon interrupt {% endblock title %}

{% block subcontent %}
  <h1 class="text-center">Are you sure you want to delete this pigeon interrupt ? </h1>
  <form  method="post" class="text-center">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes</button>
    <a href="{% url 'pigeonInterrupts:pigeon_interrupt_list' %}" class="btn btn-secondary">Cancel</a>
  </form>    
{% endblock %}

CommandCenter/pigeonInterrupts/templates/pigeonInterrupts/pigeon_interrupt_list.html
<!-- Extend the base layout from the pigeonInterrupts/layout.html -->
{% extends "pigeonInterrupts/layout.html" %}

{% block title %} Pigeon deterrent logs {% endblock %}

{% block subcontent %}
    <h1 class="text-center">Interrupt logs</h1>
    <form  method="GET" class="text-center" action="{% url 'pigeonInterrupts:pigeon_interrupt_list' %}">
        <label for="quantity">Logs amount :</label>
        <input type="number" id="quantity" name="quantity" min="0" max="30" placeholder="Pass number of logs">
        <button type="submit" class="btn btn-warning">Apply</button>
      </form>   
    <table class="table table-bordered table-striped ">
        <thead class="thead-dark">
            <tr>
                <th>Time</th>
                <th>PIRSensor</th>
                <th>CameraSensor</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for interrupt_record in pigeons_interrupts %}
            <tr>
                <td>{{ interrupt_record.Time }} </td>
                <td>{{ interrupt_record.PIRSensor }} </td>
                <td>{{ interrupt_record.CameraSensor }} </td>
                <td>
                    <a href="{% url 'pigeonInterrupts:pigeon_interrupt_delete' interrupt_record.id %}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            {% empty %}
                <p>No logs recorded</p>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}