CommandCenter/CommandCenter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mainApp.urls", namespace="main")),
    path(
        "pigeon_interrupts/",
        include("pigeonInterrupts.urls", namespace="pigeon_interrupts"),
    ),
    path("weather/", include("weatherApp.urls", namespace="weather_conditions")),
]

CommandCenter/mainApp/urls.py
from django.urls import path
from . import views

app_name = "mainApp"
urlpatterns = [
    path("", views.home_view, name="home"),
]

CommandCenter/pigeonInterrupts/urls.py
from django.urls import path
from . import views

app_name = "pigeonInterrupts"
urlpatterns = [
    path("", views.home_view, name="home"),
    path("list/", views.pigeon_interrupt_list_view, name="pigeon_interrupt_list"),
    path(
        "delete/<int:id>/",
        views.pigeon_interrupt_delete_view,
        name="pigeon_interrupt_delete",
    ),
]

CommandCenter/weatherApp/urls.py
from django.urls import path
from . import views

app_name = "weatherApp"
urlpatterns = [
    path("", views.home_view, name="home"),
    path("list/", views.weather_conditions_list_view, name="weather_conditions_list"),
    path(
        "delete/<int:id>/",
        views.weather_conditions_delete_view,
        name="weather_conditions_delete",
    ),
    path(
        "create/",
        views.weather_conditions_create_view,
        name="weather_conditions_create",
    ),
    path(
        "update/<int:id>/",
        views.weather_conditions_update_view,
        name="weather_conditions_update",
    ),
]

CommandCenter/weatherApp/models.py
from django.db import models
from django.core.exceptions import ValidationError
from enum import Enum


class TemperatureRange(Enum):
    """
    Choices class maping temperature info to emoji
    """

    FREEZING = "\U0001F976"
    COLD = "\U0001F628"
    COOL = "\U0001F610"
    MILD = "\U0001F642"
    WARM = "\U0001F604"
    HOT = "\U0001F613"
    SCHORCHING = "\U0001F975"


# Create your models here.
class WeatherConditions(models.Model):
    """
    Model contains:
    - time of weather info captured,
    - temperature,
    - additional information.
    """

    condition_id = models.AutoField(primary_key=True)
    time = models.DateTimeField(auto_now=True)
    temperature = models.DecimalField(max_digits=5, decimal_places=2)
    additional_info = models.CharField(max_length=100, default="")

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(time__isnull=False), name="time_is_not_null"
            ),
            models.CheckConstraint(
                check=models.Q(temperature__gt=-55), name="temperature_gt_-55"
            ),
            models.CheckConstraint(
                check=models.Q(temperature__lt=125), name="temperature_lt_125"
            ),
        ]

    def __str__(self) -> str:
        return f"Weather conditions captured at: {self.time}. Temerature: {self.temperature}\N{DEGREE SIGN} {self.temperature_emoji.value}. {self.additional_info}"

    def clean(self) -> None:
        if self.temperature < -55 or self.temperature > 125:
            raise ValidationError("Temperature beyond sensor's range")

    @property
    def temperature_emoji(self) -> TemperatureRange:
        if self.temperature < -10:
            return TemperatureRange.FREEZING
        elif self.temperature < 0:
            return TemperatureRange.COLD
        elif self.temperature < 13:
            return TemperatureRange.COOL
        elif self.temperature < 18:
            return TemperatureRange.MILD
        elif self.temperature < 29:
            return TemperatureRange.WARM
        elif self.temperature < 35:
            return TemperatureRange.HOT
        else:
            return TemperatureRange.SCHORCHING

CommandCenter/weatherApp/forms.py
from django import forms
from .models import WeatherConditions


class WeatherConditionsForm(forms.ModelForm):
    class Meta:
        model = WeatherConditions
        fields = "__all__"
        labels = {
            "condition_id": "Condition ID",
            "time": "Time",
            "temperature": "Temperature",
            "additional_info": "Additional information",
        }
        widgets = {
            "condition_id": forms.NumberInput(
                attrs={"placeholder": "e.g. 1", "class": "form-control"}
            ),
            "time": forms.DateTimeField(),
            "temperature": forms.NumberInput(
                attrs={"placeholder": "25.5", "class": "form-control"}
            ),
            "additional_info": forms.TextInput(
                attrs={"placeholder": "e.g Good weather...", "class": "form-control"}
            ),
        }

CommandCenter/weatherApp/logic/controller.py
from typing import Protocol, List
import logging
import schedule
import time
import threading
from weatherApp.models import WeatherConditions
from weatherApp.logic.temperature_sensor import W1TemperatureSensor, TemperatureSensor
from weatherApp.logic.display_interfaces import (
    DisplayInterface,
    WebAppWeateherDisplayInterface,
    availavle_display_interfaces,
)
from CommandCenter.config import Config

logger = logging.getLogger(__name__)


class Controller(Protocol):
    def start_logic(self): ...

    def stop_logic(self): ...


class WeatherConditionsController:
    def __init__(
        self,
        temperature_sensor: TemperatureSensor,
        display_interfaces_list: List[DisplayInterface],
        record_data_period: int,
    ) -> None:
        self.temperature_sensor = temperature_sensor
        self.display_interfaces_list = display_interfaces_list
        self.record_data_period = record_data_period

    def start_logic(self, is_stopped) -> None:
        schedule.every(self.record_data_period).seconds.do(self.display_data)
        try:
            while not is_stopped():
                schedule.run_pending()
                time.sleep(1)
        except KeyboardInterrupt:
            logger.error("KeyboardInterrupt caught. Closing the controller!")
        finally:
            self.stop_logic()

    def display_data(self) -> None:
        temperature = self.temperature_sensor.get_temperature()
        additional_info = self.temperature_sensor.get_sensor_info()
        data = WeatherConditions(
            temperature=temperature, additional_info=additional_info
        )

        for display_interface in self.display_interfaces_list:
            display_interface.display(data)

    def stop_logic(self) -> None:
        pass


class WeatherConditionsMainLogic(threading.Thread):
    def __init__(
        self,
        display_interfaces_list_str: list[str] | None,
        config: Config,
        temperature_sensor: TemperatureSensor = W1TemperatureSensor(),
    ) -> None:
        super().__init__(daemon=True)
        self.config = config
        self._stop_event = threading.Event()
        self.display_interfaces_list: list[DisplayInterface] = (
            self.prepare_display_interfaces(display_interfaces_list_str)
        )
        self.temperature_sensor = temperature_sensor
        self.controller: Controller = WeatherConditionsController(
            self.temperature_sensor,
            self.display_interfaces_list,
            self.config.record_data_period,
        )

    def prepare_display_interfaces(
        self, display_interfaces_list_str: list[str] | None
    ) -> list[DisplayInterface]:
        default_display_interfaces_list: list[DisplayInterface] = [
            WebAppWeateherDisplayInterface(self.config)
        ]
        if display_interfaces_list_str is None:
            return default_display_interfaces_list
        for interface_name in set(display_interfaces_list_str):
            display_interface = availavle_display_interfaces.get(
                interface_name.lower(), None
            )
            if display_interface is not None:
                default_display_interfaces_list.append(display_interface(self.config))
        return default_display_interfaces_list

    def run(self):
        self.controller.start_logic(self._stop_event.is_set)

    def stop(self):
        self._stop_event.set()

CommandCenter/weatherApp/views.py
from django.shortcuts import render, redirect

# Create your views here.
from .forms import WeatherConditionsForm
from .models import WeatherConditions


def home_view(request):
    return render(request, "weatherApp/home.html")


def weather_conditions_create_view(request):
    form = WeatherConditionsForm()
    if request.method == "POST":
        form = WeatherConditionsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("weatherApp:weather_conditions_list")
    return render(request, "weatherApp/weather_conditions_create.html", {"form": form})


def weather_conditions_list_view(request):
    quantity_raw = request.GET.get("quantity")
    if quantity_raw != "" and quantity_raw is not None:
        quantity = int(quantity_raw)
    else:
        quantity = 5
    weather_conditions = (
        WeatherConditions.objects.all().order_by("time").reverse()[:quantity]
    )
    return render(
        request,
        "weatherApp/weather_conditions_list.html",
        {"weather_conditions": weather_conditions},
    )


def weather_conditions_update_view(request, id):
    product = WeatherConditions.objects.get(condition_id=id)
    form = WeatherConditionsForm()
    if request.method == "POST":
        form = WeatherConditionsForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect("weatherApp:weather_conditions_list")
    return render(request, "weatherApp/weather_conditions_create.html", {"form": form})


def weather_conditions_delete_view(request, id):
    weather_condition = WeatherConditions.objects.get(condition_id=id)
    if request.method == "POST":
        weather_condition.delete()
        return redirect("weatherApp:weather_conditions_list")
    return render(
        request,
        "weatherApp/weather_conditions_delete.html",
        {"weather_condition": weather_condition},
    )

CommandCenter/weatherApp/templates/weatherApp/home.html
<!-- Extend the base layout from the weatherApp/layout.html -->
{% extends "weatherApp/layout.html" %}

{% block title %} Weather conditions {% endblock %}

{% block subcontent %}
  <div class="jumbotron text-center">
    <h1 class="display-4">Welcome to the weather conditions logs</h1>
    <hr class="my-4">
    <p>
        Use the navigation bar to add, view, update or delete weather conditions logs.
    </p>
    <a href="{% url 'weatherApp:weather_conditions_list' %}" class="btn btn-primary btn-lg" role="button">View records</a>
  </div>
{% endblock %}

CommandCenter/weatherApp/templates/weatherApp/layout.html
<!-- Extend the base layout from the mainApp:layout.html -->
{% extends "mainApp/layout.html" %}
{% comment %} Used parts of tempaltes from NetNinja's django course {% endcomment %}
{% block title %} Weather conditions logs {% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark"> 
    <a class="navbar-brand" href="{% url 'pigeonInterrupts:home' %}">Weather conditions app</a> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="true" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">  
        <ul class="navbar-nav">  
            <li class="nav-item">
                <a class="nav-link" href="{% url 'weatherApp:weather_conditions_list' %}">Show recorded weather conditions</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'weatherApp:weather_conditions_create' %}">Add recorded weather condition</a>
            </li>
        </ul>
    </div>
</nav>
<div class="subcontent">
    {% block subcontent %}
    
    {% endblock  %}
</div>
{% endblock %}

CommandCenter/weatherApp/templates/weatherApp/weather_conditions_create.html
<!-- Extend the base layout from the weatherApp/layout.html -->
{% extends "weatherApp/layout.html" %}

{% block title %} Weather conditions creation {% endblock %}

{% block content %}
<h1 class="text-center">Weather conditions</h1>
<form method="POST" class="jumbotron">
    {% csrf_token %}
    {{form}}
    <button class="btn btn-success btn-block" type="submit">Save record</button>
</form>
{% endblock %}

CommandCenter/weatherApp/templates/weatherApp/weather_conditions_delete.html
<!-- Extend the base layout from the weatherApp/layout.html -->
{% extends "weatherApp/layout.html" %}

{% block title %} Delete weather condition {% endblock title %}

{% block subcontent %}
  <h1 class="text-center">Are you sure you want to delete this record ? </h1>
  <form  method="post" class="text-center">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes</button>
    <a href="{% url 'weatherApp:weather_conditions_list' %}" class="btn btn-secondary">Cancel</a>
  </form>    
{% endblock %}

CommandCenter/weatherApp/templates/weatherApp/weather_conditions_list.html
<!-- Extend the base layout from the pigeonInterrupts/layout.html -->
{% extends "weatherApp/layout.html" %}

{% block title %} Weather conditions logs {% endblock %}

{% block subcontent %}
    <h1 class="text-center">Weather conditions logs</h1>
    <form  method="GET" class="text-center" action="{% url 'weatherApp:weather_conditions_list' %}">
        <label for="quantity">Logs amount :</label>
        <input type="number" id="quantity" name="quantity" min="0" max="30" placeholder="Pass number of logs">
        <button type="submit" class="btn btn-warning">Apply</button>
      </form>   
    <table class="table table-bordered table-striped ">
        <thead class="thead-dark">
            <tr>
                <th>Time</th>
                <th>Temperature</th>
                <th>Status</th>
                <th>Info</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for weather_condition in weather_conditions %}
            <tr>
                <td>{{ weather_condition.time }} </td>
                <td>{{ weather_condition.temperature }} &deg;C</td>
                <td>{{ weather_condition.temperature_emoji.value }} </td>
                <td>{{ weather_condition.additional_info }} </td>
                <td>
                    <a href="{% url 'weatherApp:weather_conditions_update' weather_condition.condition_id %}" class="btn btn-warning" >Update</a>
                    <a href="{% url 'weatherApp:weather_conditions_delete' weather_condition.condition_id %}" class="btn btn-danger" >Delete</a>
                </td>
            </tr>
            {% empty %}
                <p>No logs recorded</p>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}